export const COLLECTIONS = {
  USERS: "users",
  BOOKINGS: "bookings",
  JOBS: "jobs",
  INSPECTIONS: "inspections",
  LEADS: "leads",
  SALES_ACTIVITIES: "salesActivities",
  SALES_TASKS: "salesTasks",
  CONTACT_ORGANIZATIONS: "contactOrganizations",
  ORGANIZATION_CONTACTS: "organizationContacts",
  FILMS: "films",
  FILM_CLAIMS: "filmClaims",
  QUOTES: "quotes",
  CALENDAR_EVENTS: "calendarEvents",
  CALENDAR_TOKENS: "calendarTokens",
  WORKS_REGISTER: "worksRegister",
  NOTIFICATIONS: "notifications",
  MAIL: "mail",
  ANALYTICS_DAILY: "analyticsDaily",
  AI_INSIGHTS: "aiInsights",
  FLEET_VEHICLES: "fleetVehicles",
} as const;
