import { Timestamp } from "firebase/firestore";
import type { ContactOrganization, OrganizationContact } from "./types";

// Create a single timestamp for all initial data to avoid repeated Timestamp.now() calls
const INITIAL_TIMESTAMP = Timestamp.fromDate(new Date("2025-01-01T00:00:00Z"));

// ============================================
// ORGANIZATIONS DATA
// ============================================

const unsortedOrganizations: ContactOrganization[] = [
  // ASI Staff
  {
    id: "org-asi",
    name: "ASI Australia",
    category: "asi_staff",
    type: "partner",
    status: "active",
    abn: "",
    address: {
      street: "",
      suburb: "Melbourne",
      state: "VIC",
      postcode: "",
      country: "Australia",
    },
    sites: [],
    phone: "",
    email: "admin@asi-australia.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Trade Clients
  {
    id: "org-bss",
    name: "Bus Services & Solutions",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "",
    address: {
      street: "",
      suburb: "",
      state: "VIC",
      postcode: "",
      country: "Australia",
    },
    sites: [
      {
        id: "site-bss-main",
        name: "Main Location",
        address: {
          street: "",
          suburb: "",
          state: "VIC",
          postcode: "",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "0406 807 234",
    email: "accounts@bssvic.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-eurohub",
    name: "Eurohub",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "85 620 099 756",
    address: {
      street: "706 Lorimer St",
      suburb: "Port Melbourne",
      state: "VIC",
      postcode: "3207",
      country: "Australia",
    },
    sites: [
      {
        id: "site-eurohub-main",
        name: "Port Melbourne",
        address: {
          street: "706 Lorimer St",
          suburb: "Port Melbourne",
          state: "VIC",
          postcode: "3207",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "(03) 7035 3777",
    email: "Accounts@eurohub.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-harden",
    name: "Harden Packaging",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "56 454 174 836",
    address: {
      street: "29 Korong Rd",
      suburb: "Heidelberg West",
      state: "VIC",
      postcode: "3081",
      country: "Australia",
    },
    sites: [
      {
        id: "site-harden-main",
        name: "Heidelberg West",
        address: {
          street: "29 Korong Rd",
          suburb: "Heidelberg West",
          state: "VIC",
          postcode: "3081",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "03 9458 2533",
    email: "sales@hardenpackaging.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-irizar",
    name: "Irizar Asia Pacific",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "53 162 612 795",
    address: {
      street: "49 Greenhills Rd",
      suburb: "Pakenham",
      state: "VIC",
      postcode: "3810",
      country: "Australia",
    },
    sites: [
      {
        id: "site-irizar-main",
        name: "Pakenham",
        address: {
          street: "49 Greenhills Rd",
          suburb: "Pakenham",
          state: "VIC",
          postcode: "3810",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "",
    email: "",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-lsh",
    name: "LSH AUTO (MELBOURNE) Pty Ltd",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "77 618 554 635",
    address: {
      street: "135 Kings Way",
      suburb: "South Melbourne",
      state: "VIC",
      postcode: "3205",
      country: "Australia",
    },
    sites: [
      {
        id: "site-lsh-main",
        name: "South Melbourne",
        address: {
          street: "135 Kings Way",
          suburb: "South Melbourne",
          state: "VIC",
          postcode: "3205",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "0406 202 117",
    email: "john.mack@mbmelbourne.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-mcc",
    name: "Melbournes Cheapest Cars",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "43 666 685 589",
    address: {
      street: "6 Lennox St",
      suburb: "Moorabbin",
      state: "VIC",
      postcode: "3189",
      country: "Australia",
    },
    sites: [
      {
        id: "site-mcc-main",
        name: "Moorabbin",
        address: {
          street: "6 Lennox St",
          suburb: "Moorabbin",
          state: "VIC",
          postcode: "3189",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "0418 105 039",
    email: "jimmacris68@gmail.com",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-millennium",
    name: "Millennium Auto (Carguru)",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "74 533 584 563",
    address: {
      street: "146-148 Thistlethwaite St",
      suburb: "South Melbourne",
      state: "VIC",
      postcode: "3205",
      country: "Australia",
    },
    sites: [
      {
        id: "site-millennium-main",
        name: "South Melbourne",
        address: {
          street: "146-148 Thistlethwaite St",
          suburb: "South Melbourne",
          state: "VIC",
          postcode: "3205",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "0406 265 933",
    email: "sales@millenniumauto.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-nuline",
    name: "Nuline Charter Pty Ltd",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "25 981 499 326",
    address: {
      street: "36-44 Whiteside Rd",
      suburb: "Clayton South",
      state: "VIC",
      postcode: "3169",
      country: "Australia",
    },
    sites: [
      {
        id: "site-nuline-main",
        name: "Clayton South",
        address: {
          street: "36-44 Whiteside Rd",
          suburb: "Clayton South",
          state: "VIC",
          postcode: "3169",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "0413 245 940",
    email: "charlie@nulinecharter.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-pagebros",
    name: "Page Bros RV",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "52 408 358 400",
    address: {
      street: "893-895 Princes Hwy",
      suburb: "Springvale",
      state: "VIC",
      postcode: "3171",
      country: "Australia",
    },
    sites: [
      {
        id: "site-pagebros-main",
        name: "Springvale",
        address: {
          street: "893-895 Princes Hwy",
          suburb: "Springvale",
          state: "VIC",
          postcode: "3171",
          country: "Australia",
        },
        isDefault: true,
      },
    ],
    phone: "(03) 9786 1000",
    email: "mark@pagebrosrv.com.au",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "org-mckenzies",
    name: "McKenzie's Tourist Services Pty Ltd",
    category: "trade_client",
    type: "customer",
    status: "active",
    abn: "",
    address: {
      street: "13 Lilydale Road",
      suburb: "Healesville",
      state: "VIC",
      postcode: "3777",
      country: "Australia",
    },
    sites: [
      {
        id: "site-mckenzies-main",
        name: "Healesville",
        address: {
          street: "13 Lilydale Road",
          suburb: "Healesville",
          state: "VIC",
          postcode: "3777",
          country: "Australia",
        },
        isDefault: true,
        notes: "Enter off Crisp Street",
      },
    ],
    phone: "(03) 5962 5088",
    email: "mckenzies@bigpond.com",
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
];

// Sort organizations alphabetically by name
export const initialOrganizations = unsortedOrganizations.sort((a, b) =>
  a.name.localeCompare(b.name)
);

// ============================================
// CONTACTS DATA
// ============================================

const unsortedContacts: OrganizationContact[] = [
  // ASI Staff
  {
    id: "contact-josh",
    organizationId: "org-asi",
    firstName: "Joshua",
    lastName: "Hyde",
    email: "joshua@asi-australia.com.au",
    mobile: "0437 087 042",
    role: "management",
    jobTitle: "Director",
    status: "active",
    isPrimary: false,
    hasPortalAccess: true,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-jaydan",
    organizationId: "org-asi",
    firstName: "Jaydan",
    lastName: "Hyde",
    email: "jaydan@asi-australia.com.au",
    mobile: "0457 183 494",
    role: "management",
    jobTitle: "Administration Manager",
    status: "active",
    isPrimary: true,
    hasPortalAccess: true,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-bobby",
    organizationId: "org-asi",
    firstName: "Bobby",
    lastName: "McLaren",
    email: "bobby@asi-australia.com.au",
    mobile: "0427 316 318",
    role: "management",
    jobTitle: "Operations Manager",
    status: "active",
    isPrimary: false,
    hasPortalAccess: true,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Bus Services & Solutions
  {
    id: "contact-bss-johnathan",
    organizationId: "org-bss",
    firstName: "Johnathan",
    lastName: "",
    email: "johnathan@bssvic.com.au",
    phone: "0406 807 234",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-bss-anderson",
    organizationId: "org-bss",
    firstName: "Anderson",
    lastName: "Silva",
    email: "anderson@bssvic.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Eurohub
  {
    id: "contact-eurohub-sales",
    organizationId: "org-eurohub",
    firstName: "Sales",
    lastName: "",
    email: "sales@eurohub.com.au",
    phone: "(03) 7035 3777",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-eurohub-milo",
    organizationId: "org-eurohub",
    firstName: "Milo",
    lastName: "",
    email: "milo@eurohub.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Harden Packaging
  {
    id: "contact-harden-sales",
    organizationId: "org-harden",
    firstName: "Sales",
    lastName: "",
    email: "sales@hardenpackaging.com.au",
    phone: "03 9458 2533",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // LSH AUTO
  {
    id: "contact-lsh-john",
    organizationId: "org-lsh",
    firstName: "John",
    lastName: "Mack",
    email: "john.mack@mbmelbourne.com.au",
    mobile: "0406 202 117",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-lsh-diana",
    organizationId: "org-lsh",
    firstName: "Diana",
    lastName: "Gonzaga",
    email: "Diana.gonzaga@mbmelbourne.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-lsh-nabil",
    organizationId: "org-lsh",
    firstName: "Nabil",
    lastName: "Girgis",
    email: "accounts.mbm@mbmelbourne.com.au",
    role: "billing",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Melbournes Cheapest Cars
  {
    id: "contact-mcc-jim",
    organizationId: "org-mcc",
    firstName: "Jim",
    lastName: "Macris",
    email: "jimmacris68@gmail.com",
    mobile: "0418 105 039",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-mcc-pradeep",
    organizationId: "org-mcc",
    firstName: "Pradeep",
    lastName: "Wijesingha",
    email: "pradeep.w@autonxt.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Millennium Auto
  {
    id: "contact-millennium-guru",
    organizationId: "org-millennium",
    firstName: "Guru",
    lastName: "",
    email: "sales@millenniumauto.com.au",
    mobile: "0406 265 933",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Nuline Charter
  {
    id: "contact-nuline-charlie",
    organizationId: "org-nuline",
    firstName: "Charlie",
    lastName: "Crespo",
    email: "charlie@nulinecharter.com.au",
    mobile: "0413 245 940",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-nuline-jason",
    organizationId: "org-nuline",
    firstName: "Jason",
    lastName: "Fletcher",
    email: "Jason@nulinecharter.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-nuline-ash",
    organizationId: "org-nuline",
    firstName: "Ash",
    lastName: "",
    email: "ash@nulinecharter.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-nuline-andrew",
    organizationId: "org-nuline",
    firstName: "Andrew",
    lastName: "McDonald",
    email: "info@nulinecharter.com.au",
    role: "primary",
    status: "active",
    isPrimary: false,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // Page Bros RV
  {
    id: "contact-pagebros-mark",
    organizationId: "org-pagebros",
    firstName: "Mark",
    lastName: "Cunningham",
    email: "mark@pagebrosrv.com.au",
    phone: "(03) 9786 1000",
    role: "primary",
    status: "active",
    isPrimary: true,
    hasPortalAccess: false,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  // McKenzie's Tourist Services
  {
    id: "contact-mckenzies-brad",
    organizationId: "org-mckenzies",
    firstName: "Brad",
    lastName: "Sanders",
    email: "mckenzies@bigpond.com",
    mobile: "0429 139 899",
    role: "primary",
    jobTitle: "General Manager",
    status: "active",
    isPrimary: true,
    hasPortalAccess: true,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
  {
    id: "contact-mckenzies-adrian",
    organizationId: "org-mckenzies",
    firstName: "Adrian",
    lastName: "",
    email: "mckenzies@bigpond.com",
    mobile: "0427 637 673",
    role: "primary",
    jobTitle: "Operations Manager",
    status: "active",
    isPrimary: false,
    hasPortalAccess: true,
    createdAt: INITIAL_TIMESTAMP,
    updatedAt: INITIAL_TIMESTAMP,
  },
];

// Sort contacts alphabetically by first name, then last name
export const initialContacts = unsortedContacts.sort((a, b) => {
  const nameA = `${a.firstName} ${a.lastName}`.trim();
  const nameB = `${b.firstName} ${b.lastName}`.trim();
  return nameA.localeCompare(nameB);
});

// ============================================
// ASI STAFF FOR BOOKINGS
// ============================================

const unsortedStaff: { id: string; name: string; type: "asi_staff" | "subcontractor" }[] = [
  { id: "staff-josh", name: "Joshua Hyde", type: "asi_staff" },
  { id: "staff-jaydan", name: "Jaydan Hyde", type: "asi_staff" },
  { id: "staff-bobby", name: "Bobby McLaren", type: "asi_staff" },
];

export const asiStaff = unsortedStaff.sort((a, b) => a.name.localeCompare(b.name));
